### ISSUE TITLE
Thanks great work!

### ISSUE THREAD

**Issue by sirlordt** [kommander/thread-puddle#2]
Hey thanks great work!.

You had plan to support typescript?

**Comment by kommander** [comment]
Thanks, yes, many plans :) Little time. Would be happy to support it. Do you know how one could forward the types of the dynamically imported worker to the proxy object, so the compiler and editor know what types are exported from a worker? Haven't had time to figure that out yet.

**Comment by kommander** [comment]
@sirlordt Startet typescript support, works fine so far: #4
